# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
#    - go mod tidy
    # you may remove this if you don't need go generate
#    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  id: "sacgo"
  binary: "sacgo"
  goos:
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
archives:
- replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "v1.2.0-pre-release"